# Generated by Django 4.2.3 on 2024-03-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0002_chathistory_chatbot_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='message',
            new_name='user_input',
        ),
    ]
