# Generated by Django 4.2.3 on 2024-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0003_rename_message_chathistory_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chatbot_response',
            field=models.CharField(default='', max_length=255),
        ),
    ]
