# Generated by Django 4.2.3 on 2024-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0004_alter_chathistory_chatbot_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chatbot_response',
            field=models.CharField(default='', max_length=20),
        ),
    ]
