# Generated by Django 4.2.3 on 2024-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0007_medicine_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
