# Generated by Django 4.2.3 on 2024-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0009_remove_medicine_alternative_id_medicine_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='alternative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
