# Generated by Django 4.2.3 on 2024-03-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0010_alter_medicine_alternative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='alternative',
            new_name='alternatives',
        ),
    ]
