# Generated by Django 4.2.3 on 2024-03-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0012_alter_medicine_alternatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='alternatives',
        ),
    ]
