# Generated by Django 4.2.3 on 2024-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediverse', '0013_remove_medicine_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='alternatives',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
